# Generated by Django 6.0.1 on 2026-01-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                ("cpf_cnpj", models.CharField(max_length=20, verbose_name="CPF/CNPJ")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("endereco", models.CharField(max_length=255, verbose_name="Endereço")),
                (
                    "data_cadastro",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de cadastro"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=150, verbose_name="Descrição"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
        ),
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PC", "Computador"),
                            ("NB", "Notebook"),
                            ("IMP", "Impressora"),
                            ("MON", "Monitor"),
                            ("PER", "Periférico"),
                        ],
                        max_length=3,
                        verbose_name="Tipo",
                    ),
                ),
                ("marca", models.CharField(max_length=100, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "numero_serie",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Número de série"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipamentos",
                        to="core.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_os",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número da OS"
                    ),
                ),
                (
                    "data_abertura",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data de abertura"
                    ),
                ),
                (
                    "data_fechamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de fechamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AB", "Aberta"),
                            ("AN", "Em andamento"),
                            ("AP", "Aguardando peça"),
                            ("CO", "Concluída"),
                            ("CA", "Cancelada"),
                        ],
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                ("defeito_relatado", models.TextField(verbose_name="Defeito relatado")),
                (
                    "diagnostico",
                    models.TextField(blank=True, verbose_name="Diagnóstico"),
                ),
                ("solucao", models.TextField(blank=True, verbose_name="Solução")),
                (
                    "valor_servico",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor do serviço"
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordens_servico",
                        to="core.equipamento",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordens_servico",
                        to="core.tecnico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=150, verbose_name="Descrição"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("data_pagamento", models.DateField(verbose_name="Data de pagamento")),
                (
                    "categoria",
                    models.CharField(max_length=50, verbose_name="Categoria"),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despesas",
                        to="core.ordemservico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=150, verbose_name="Descrição"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateField(verbose_name="Data de recebimento"),
                ),
                (
                    "metodo_pagamento",
                    models.CharField(max_length=30, verbose_name="Método de pagamento"),
                ),
                (
                    "status_pagamento",
                    models.CharField(max_length=30, verbose_name="Status do pagamento"),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receitas",
                        to="core.ordemservico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdemServicoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_servico",
                        to="core.ordemservico",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.servico"
                    ),
                ),
            ],
        ),
    ]
