# Generated by Django 6.0.1 on 2026-01-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="numero_os",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Número da OS",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="status",
            field=models.CharField(
                choices=[
                    ("AB", "Aberta"),
                    ("AN", "Em andamento"),
                    ("AP", "Aguardando peça"),
                    ("CO", "Concluída"),
                    ("CA", "Cancelada"),
                ],
                default="AB",
                max_length=2,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="tecnico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordens_servico",
                to="core.tecnico",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="valor_servico",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Valor do serviço",
            ),
        ),
    ]
