# Generated by Django 6.0.1 on 2026-01-27 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_ordemservico_numero_os_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="despesa",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="despesa",
            name="data_pagamento",
        ),
        migrations.RemoveField(
            model_name="despesa",
            name="ordem_servico",
        ),
        migrations.AddField(
            model_name="despesa",
            name="data_despesa",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data"
            ),
        ),
        migrations.AddField(
            model_name="despesa",
            name="observacao",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
        migrations.AddField(
            model_name="despesa",
            name="status",
            field=models.CharField(
                choices=[("PE", "Pendente"), ("PA", "Paga")],
                default="PE",
                max_length=2,
                verbose_name="Status",
            ),
        ),
    ]
