# Generated by Django 6.0.1 on 2026-01-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_despesa_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PC", "Computador"),
                    ("NB", "Notebook"),
                    ("IMP", "Impressora"),
                    ("MON", "Monitor"),
                    ("TV", "Televisão"),
                    ("PER", "Periférico"),
                ],
                max_length=3,
                verbose_name="Tipo",
            ),
        ),
    ]
