# Generated by Django 6.0.1 on 2026-02-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_equipamento_tipo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["nome"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AlterModelOptions(
            name="despesa",
            options={
                "ordering": ["-data_despesa"],
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
            },
        ),
        migrations.AlterModelOptions(
            name="equipamento",
            options={
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="ordemservico",
            options={
                "ordering": ["-data_abertura"],
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
            },
        ),
        migrations.AlterModelOptions(
            name="ordemservicoservico",
            options={
                "verbose_name": "Serviço da OS",
                "verbose_name_plural": "Serviços da OS",
            },
        ),
        migrations.AlterModelOptions(
            name="receita",
            options={
                "ordering": ["-data_recebimento"],
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
            },
        ),
        migrations.AlterModelOptions(
            name="servico",
            options={
                "ordering": ["descricao"],
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
        migrations.AlterModelOptions(
            name="tecnico",
            options={
                "ordering": ["nome"],
                "verbose_name": "Técnico",
                "verbose_name_plural": "Técnicos",
            },
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf_cnpj",
            field=models.CharField(max_length=20, unique=True, verbose_name="CPF/CNPJ"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="ordemservicoservico",
            name="quantidade",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
        ),
        migrations.AlterField(
            model_name="tecnico",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
    ]
